# Generated by Django 2.1.10 on 2019-07-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('Enterprise', 'ent'), ('Professional', 'pro'), ('Free', 'free')], default='Free', max_length=30)),
                ('price', models.IntegerField(default=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='address_one',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='address_two',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='city',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='state',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Membership'),
        ),
    ]
