# Generated by Django 2.1.10 on 2019-07-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20190708_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user_rec',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
